DROP TABLE IF EXISTS #__joaktree_citations ;
DROP TABLE IF EXISTS #__joaktree_citations ;
DROP TABLE IF EXISTS #__joaktree_documents ;
DROP TABLE IF EXISTS #__joaktree_gedcom_objectlines ;
DROP TABLE IF EXISTS #__joaktree_gedcom_objects ;
DROP TABLE IF EXISTS #__joaktree_locations ;
DROP TABLE IF EXISTS #__joaktree_logremovals;
DROP TABLE IF EXISTS #__joaktree_logs ;
DROP TABLE IF EXISTS #__joaktree_maps ;
DROP TABLE IF EXISTS #__joaktree_notes;
DROP TABLE IF EXISTS #__joaktree_persons;
DROP TABLE IF EXISTS #__joaktree_person_documents ;
DROP TABLE IF EXISTS #__joaktree_person_events ;
DROP TABLE IF EXISTS #__joaktree_person_names ;
DROP TABLE IF EXISTS #__joaktree_person_notes ;
DROP TABLE IF EXISTS #__joaktree_registry_items ;
DROP TABLE IF EXISTS #__joaktree_relations ;
DROP TABLE IF EXISTS #__joaktree_relation_events ;
DROP TABLE IF EXISTS #__joaktree_relation_notes ;
DROP TABLE IF EXISTS #__joaktree_repositories ;
DROP TABLE IF EXISTS #__joaktree_sources ;
DROP TABLE IF EXISTS #__joaktree_tree_persons ;